project:
  type: website
  output-dir: docs 

website:
  title: "LAQUIPE"
  favicon: assets/logo-pequena.png
  navbar:
    logo: assets/logo-pequena.png
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - artigos.qmd
      - linhas.qmd
      - text: Blog
        href: blog/index.qmd
      - text: Calend√°rios
        file: calendarios.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

